Repository costcook-team/costcook-frontend, pull requests merged in 2024-11, with the labels that each got.

#46 Feat: 즐겨찾기 등록 및 삭제 API 연동, 가짜 API 기반 즐겨찾기 화면 구현(즐겨찾기 목록 조회 및 삭제 API 연동 전)
  src/components/display/RecipeCard.jsx
  src/components/display/ReviewCard.jsx
  src/components/layout/Footer.jsx
  src/pages/FavoritePage.jsx
  src/pages/RecipePage.jsx
  src/pages/SearchPage.jsx
  src/services/favorite.api.js
  src/utils/sessionStorageUtil.js
Labels: enhancement

#48 Feat/home page
  src/components/display/RecipeListStyle.jsx
  src/components/display/ReviewCard.jsx
  src/pages/BudgetPage.jsx
  src/pages/HomePage.jsx
  src/pages/RecipeDetail.jsx
  src/pages/RecipePage.jsx
  src/services/recipe.api.js
  src/utils/sort.js
Labels: documentation

#47 Feat/레시피 상세 페이지 스타일링
  index.html
  src/components/Input/RecipeEvaluation.jsx
  src/components/StarRating.jsx
  src/components/admin/SelectWrapper.jsx
  src/components/common/Button/ShareButton.jsx
  src/components/common/Button/ShareModal.jsx
  src/components/layout/Header/Header.jsx
  src/index.css
  src/pages/RecipeDetail.jsx
  src/styles/RecipeDetail.js
  src/utils/format.js
  src/utils/formatData.js
Labels: documentation

#51 Feat/admin review
  src/App.jsx
  src/components/admin/AdminDrawer.jsx
  src/components/admin/AdminHeader.jsx
  src/components/admin/AdminLayout.jsx
  src/components/admin/ExitModal.jsx
  src/components/admin/ReviewDetailModal.jsx
  src/pages/admin/AdminHome.jsx
  src/pages/admin/ReviewList.jsx
Labels: enhancement

#52 Feat: 즐겨찾기 화면 구현 및 API 연동(즐겨찾기 목록 조회, 즐겨찾기 삭제)
  public/cookbook.png
  src/App.jsx
  src/components/common/Button/RoundedButton.jsx
  src/components/layout/Main.jsx
  src/pages/FavoritePage.jsx
  src/pages/RecipeDetail.jsx
  src/services/favorite.api.js
  src/services/recipe.api.js
  src/utils/sessionStorageUtil.js
Labels: enhancement

#55 Feat/admin review
  src/components/admin/ReviewDetailModal.jsx
  src/pages/admin/ReviewList.jsx
Labels: enhancement

#56 Feat: 레시피 관련 페이지 UI 수정 및 API 연동
  package.json
  src/components/CardListContainer.jsx
  src/components/Input/RecipeEvaluation.jsx
  src/components/RecipeEvaluation.jsx
  src/components/RecipeInstructions.jsx
  src/components/RecipeReviewCard.jsx
  src/components/ReviewEditModal.jsx
  src/components/common/Button/ShareButton.jsx
  src/components/common/Button/ShareModal.jsx
  src/components/common/LoginModal.jsx
  src/components/display/RecipeCard.jsx
  src/components/display/RecipeListStyle.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header/Header.jsx
  src/components/layout/Layout.jsx
  src/components/modal/ShareModal.jsx
  src/context/Auth/AuthProvider.jsx
  src/hooks/useRecipeInfo.js
  src/pages/FavoritePage.jsx
  src/pages/HomePage.jsx
  src/pages/MyPage.jsx
  src/pages/MyReviewPage.jsx
  src/pages/OAuthVerification.jsx
  src/pages/RecipeDetail.jsx
  src/pages/RecipePage.jsx
  src/pages/SearchPage.jsx
  src/services/recipe.api.js
  src/services/review.api.js
  src/services/user.api.js
  src/styles/RecipeDetail.js
  src/utils/favoriteHandler.js
  yarn.lock
Labels: enhancement

#58 Feat : 캐러셀 회전 및 추천 페이지 남은 금액 오류 수정
  src/components/common/Carousel/Carousel.jsx
  src/components/common/Carousel/CarouselCard.jsx
  src/components/common/Carousel/MainPageCarousel.jsx
  src/components/display/RecipeListStyle.jsx
  src/context/Auth/AuthProvider.jsx
  src/pages/HomePage.jsx
  src/pages/RecommendPage.jsx
Labels: enhancement

#54 Feat/weekly detail page
  src/App.jsx
  src/components/common/ProgressBar.jsx
  src/components/display/BudgetRecipeSlide.jsx
  src/components/display/RecipeListStyle.jsx
  src/components/layout/Footer.jsx
  src/pages/BudgetPage.jsx
  src/pages/HomePage.jsx
  src/pages/RecipePage.jsx
  src/pages/WeeklyCalendar.jsx
  src/pages/WeeklyDetail.jsx
  src/services/recommend.api.js
  src/utils/dateUtil.js
Labels: documentation

#59 Feat: 닉네임 인풋 중복확인 버튼 추가 및 중복확인 API 연동
  src/components/Input/UserNicknameInput.jsx
  src/components/UserProfile.jsx
  src/components/common/Button/RoundedButton.jsx
  src/components/common/Carousel/MainPageCarousel.jsx
  src/components/display/StepIndicator.jsx
  src/pages/HomePage.jsx
  src/pages/OAuthVerification.jsx
  src/pages/ProfileUpdate.jsx
  src/utils/nicknameData.js
  src/utils/nicknameGenerator.js
  src/utils/sessionStorageUtil.js
Labels: enhancement

#60 feat : 에러 수정
  src/components/common/Carousel/MainPageCarousel.jsx
  src/pages/HomePage.jsx
  src/pages/RecommendPage.jsx
Labels: bug

#61 Feat/weekly detail page
  src/components/display/BudgetRecipeSlide.jsx
  src/hooks/useWeeklyDate.js
  src/pages/HomePage.jsx
  src/pages/RecipePage.jsx
  src/pages/WeeklyDetail.jsx
Labels: documentation

#62 Refactor: 레시피 목록 페이지에서 사용되는 드롭다운 컴포넌트 수정
  src/components/common/Button/FilterDropdownButton.jsx
  src/pages/HomePage.jsx
  src/pages/RecipePage.jsx
  src/pages/admin/RecipeList.jsx
Labels: enhancement

#64 Feat: 접근 권한 제어 컴포넌트 적용 및 일부 페이지 URL 변경
  src/App.jsx
  src/components/Auth/AdminRoute.jsx
  src/components/Auth/AllUserRoute.jsx
  src/components/Auth/PublicRoute.jsx
  src/components/Auth/UserAndGuestRoute.jsx
  src/components/Auth/UserRoute.jsx
  src/components/common/BudgetAmountSetting.jsx
  src/components/common/Carousel/MainPageCarousel.jsx
  src/components/display/BudgetRecipeSlide.jsx
  src/components/display/RecipeCard.jsx
  src/components/display/ReviewCard.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/Header/Header.jsx
  src/pages/Activities.jsx
  src/pages/BudgetPage.jsx
  src/pages/HomePage.jsx
  src/pages/ItemList.jsx
  src/pages/MyPage.jsx
  src/pages/OAuthVerification.jsx
  src/pages/ProfileUpdate.jsx
  src/pages/Review.jsx
  src/pages/SearchPage.jsx
  src/pages/UserInfo.jsx
Labels: enhancement

#65 Feat/weekly detail page
  src/pages/WeeklyDetail.jsx
Labels: documentation

#63 fix:예산 관리페이지에서 주차 상세페이지 이동 시 컨펌 모달로 변경, 예산 사용 유도 시 토스트 출력
  src/components/common/ProgressBar.jsx
  src/hooks/useWeeklyDate.js
  src/index.css
  src/pages/BudgetPage.jsx
Labels: documentation

#66 Fix: 각 페이지 별 스타일 및 로직 점검 후 변경
  src/components/Auth/AdminRoute.jsx
  src/components/Auth/UserRoute.jsx
  src/components/ConfirmationModal.jsx
  src/components/RecentKeywords.jsx
  src/components/display/RecipeCard.jsx
  src/components/layout/Header/Header.jsx
  src/hooks/useRecipeInfo.js
  src/pages/FavoritePage.jsx
  src/pages/HomePage.jsx
  src/pages/MyPage.jsx
  src/pages/OAuthVerification.jsx
  src/pages/RecipeDetail.jsx
  src/pages/SearchPage.jsx
Labels: enhancement

#78 Feat/weekly detail page
  src/hooks/useWeeklyDate.js
  src/pages/BudgetPage.jsx
  src/pages/WeeklyDetail.jsx
Labels: documentation

#79 fix:검색어 없이 검색 시 오류 수정 -> 검색해달라는 문구 추가
  src/pages/SearchPage.jsx
Labels: documentation

#80 Feat/weekly detail page
  src/pages/WeeklyDetail.jsx
Labels: documentation

#81 Fix: 푸터 화면 아래에 붙어 있도록 스타일링 수정
  src/components/layout/Footer.jsx
Labels: enhancement

#82 fix:인기레시피 슬라이드 적용(화면이 줄어듦에 따른 줄넘김 방지)
  src/components/common/Button/StartButton.jsx
  src/pages/HomePage.jsx
Labels: documentation

#83 Fix: 화면 렌더링 될 때마다 로그인 여부 파악 후 내정보 조회하도록 로직 수정
  src/App.jsx
  src/components/common/Carousel/CarouselCard.jsx
  src/context/Auth/AuthProvider.jsx
  src/main.jsx
  src/pages/MyPage.jsx
  src/services/api.js
Labels: enhancement

#84 Fix: vite 설정 파일 변경
  vite.config.js
Labels: bug

#86 Feat/favorite UI
  src/components/layout/Footer.jsx
Labels: documentation

#88 Fix: #70, #72, #74, #87 이슈 해결
  src/components/display/RecipeCard.jsx
  src/pages/FavoritePage.jsx
  src/pages/OAuthVerification.jsx
  src/pages/SearchPage.jsx
Labels: bug

#89 Fix: 이메일 인증 과정 이슈 및 프로필 이미지 null 일 경우 처리
  src/App.jsx
  src/components/ProfileImageUploader.jsx
  src/context/Auth/AuthProvider.jsx
  src/pages/MyPage.jsx
  src/pages/OAuthVerification.jsx
  src/pages/ProfileUpdate.jsx
Labels: bug

#90 Fix: 누락 변수 사용 및 로그인 상태에 의해 추천받은 레시피 렌더링되지 않는 이슈 해결
  src/App.jsx
  src/pages/MyPage.jsx
  src/pages/OAuthVerification.jsx
  src/services/recommend.api.js
  src/utils/sessionStorageUtil.js
Labels: bug

#91 feat:콘솔 로그 제거, 레시피카드 분량 및 가격이 1인분 기준으로만 나오게 수정
  src/components/ProfileImageUploader.jsx
  src/components/display/RecipeCard.jsx
  src/components/display/ReviewCard.jsx
  src/components/dropdown/DropdownMenu.jsx
  src/hooks/useRecipeInfo.js
  src/hooks/useUserInfo.js
  src/pages/BudgetPage.jsx
  src/pages/FavoritePage.jsx
  src/pages/HomePage.jsx
  src/pages/LoginPage.jsx
  src/pages/OAuthVerification.jsx
  src/pages/RecipeDetail.jsx
  src/pages/SearchPage.jsx
  src/pages/WeeklyDetail.jsx
  src/services/api.js
  src/utils/favoriteHandler.js
  src/utils/format.js
Labels: documentation

#93 Feat/front finishing work
  index.html
  public/costcook_logo.jpg
  src/components/Auth/UserRoute.jsx
  src/components/ProfileImageUploader.jsx
  src/components/RecipeInstructions.jsx
  src/components/RecipeReviewCard.jsx
  src/components/common/Button/StartButton.jsx
  src/components/common/Carousel/MainPageCarousel.jsx
  src/components/display/ImageDisplay.jsx
  src/pages/HomePage.jsx
  src/pages/MyPage.jsx
  src/pages/RecipeDetail.jsx
  src/pages/RecommendPage.jsx
Labels: documentation

#94 fix:예산 관리 페이지 가격 계산 오류 수정: 가격/분량 나누기 표기로 수정
  src/pages/BudgetPage.jsx
Labels: documentation

#95 fix: [안먹었어요] 적용 : z-index 추가
  src/components/common/Carousel/MainPageCarousel.jsx
Labels: documentation
